# -*- coding: utf-8 -*-
"""AirLine_Analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i0M8Pk9iIsoxPB3-AT66FNvu2LRbBH5G
"""

import pandas as pd
import numpy as np
from scipy import stats
import json
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.float_format', lambda x: f'{x:,.2f}')
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 150)

# PART 1: LOAD DATA

df = pd.read_excel('airline_route_profitability.xlsx')
print(f"Loaded {len(df):,} flight records with {df.shape[1]} columns.")
df.head(10)

df.describe()

df.info()

print(df['Origin'].unique())
df = df.drop(columns=['Origin' , 'Flight_Number'])

df.insert(0, 'ID', range(len(df)))
df.head(10)

print(df.isnull().sum())

NAN_COLS = ['Ancillary_Revenue' , 'Catering_Cost' , 'Handling_Cost']

df[NAN_COLS].describe()

df['Ancillary_Revenue'] = df['Ancillary_Revenue'].fillna(
    df['Ancillary_Revenue'].mean)

df['Catering_Cost'] = df['Catering_Cost'].fillna(
    df['Catering_Cost'].mean())

df['Handling_Cost'] = df['Handling_Cost'].fillna(
    df['Handling_Cost'].mean()
)

from scipy import stats
import pandas as pd

zscore_cols = ['Profit', 'Profit_Margin', 'Total_Revenue', 'Fuel_Cost', 'Flight_Hours']

for col in zscore_cols:
    df[f'{col}_zscore'] = stats.zscore(df[col])

# outliers (|Z| > 3)
for col in zscore_cols:
    outliers = df[df[f'{col}_zscore'].abs() > 3]
    print(f"{col}: {len(outliers)} outliers ({len(outliers)/len(df)*100:.2f}%)")

# PART 2: ANALYSIS 1 - OVERALL PROFIT PICTURE  (التحليل الأول)

overall = {
    'total_flights': int(len(df)),
    'avg_profit': round(df['Profit'].mean(), 2),
    'avg_profit_margin': round(df['Profit_Margin'].mean(), 2),
    'max_profit_margin': round(df['Profit_Margin'].max(), 2),
    'min_profit_margin': round(df['Profit_Margin'].min(), 2),
    'loss_flights': int((df['Profit'] < 0).sum()),
    'total_revenue': round(df['Total_Revenue'].sum(), 2),
    'total_cost': round(df['Total_Cost'].sum(), 2),
    'total_profit': round(df['Profit'].sum(), 2),
}
overall['loss_flights_pct'] = round(overall['loss_flights'] / overall['total_flights'] * 100, 2)

for k, v in overall.items():
    print(f"  {k}: {v:,}")
print()

# PART 3: ANALYSIS 2 - PROFITABILITY BY DESTINATION  (ربحية كل وجهة)

route_profitability = (
    df.groupby(['Destination', 'Route_Category'])
    .agg(
        total_flights=('Profit', 'count'),
        avg_profit_margin=('Profit_Margin', 'mean'),
        avg_profit=('Profit', 'mean'),
        total_profit=('Profit', 'sum'),
        total_revenue=('Total_Revenue', 'sum'),
        loss_flights=('Profit', lambda x: (x < 0).sum()),
        sucss_flights=('Profit', lambda x: (x > 0).sum())
    )
    .round(2)
    .sort_values('avg_profit_margin', ascending=False)
    .reset_index()
)
print(route_profitability.to_string(index=False))
print()

route_profitability.plot(
    x='Destination',
    y='avg_profit_margin',
    kind='barh',
    figsize=(10,8)
)

# PART 4: ANALYSIS 3 - SEASONAL IMPACT ON PROFIT  (تأثير الموسم على الأرباح)

season_profitability = (
    df.groupby('Season')
    .agg(
        total_flights=('Profit', 'count'),
        avg_profit_margin=('Profit_Margin', 'mean'),
        avg_load_factor=('Load_Factor', lambda x: x.mean() * 100),
        total_profit=('Profit', 'sum'),
        loss_flights=('Profit', lambda x: (x < 0).sum()),
    )
    .round(2)
    .sort_values('avg_profit_margin', ascending=False)
    .reset_index()
)
print(season_profitability.to_string(index=False))
print()

import matplotlib.pyplot as plt

plt.figure(figsize=(8,4))
plt.bar(
    season_profitability['Season'],
    season_profitability['avg_profit_margin']
)
plt.title("Profit Margin by Season")
plt.ylabel("Profit Margin %")
plt.show()

# PART 5: ANALYSIS 4 - AIRCRAFT TYPE EFFICIENCY  (كفاءة كل نوع طيارة)

aircraft_performance = (
    df.groupby(['Aircraft_Type', 'Aircraft_Capacity'])
    .agg(
        total_flights=('Profit', 'count'),
        avg_profit_margin=('Profit_Margin', 'mean'),
        avg_load_factor=('Load_Factor', lambda x: x.mean() * 100),
        avg_fuel_cost=('Fuel_Cost', 'mean'),
        total_profit=('Profit', 'sum'),
        loss_flights=('Profit', lambda x: (x < 0).sum()),
    )
    .round(2)
    .sort_values('avg_profit_margin', ascending=False)
    .reset_index()
)
print(aircraft_performance.to_string(index=False))
print()

import matplotlib.pyplot as plt

# =========================
# 1. Setup Figure (Dashboard)
# =========================
fig, axes = plt.subplots(2, 3, figsize=(20, 12))
fig.suptitle('Aircraft Efficiency Dashboard', fontsize=18, fontweight='bold')

# =========================
# Data
# =========================
aircraft = aircraft_performance['Aircraft_Type']

# =========================
# 1. Profit Margin
# =========================
axes[0, 0].bar(aircraft, aircraft_performance['avg_profit_margin'])
axes[0, 0].set_title('Profit Margin (%)')
axes[0, 0].tick_params(axis='x', rotation=45)

# =========================
# 2. Total Profit
# =========================
axes[0, 1].bar(aircraft, aircraft_performance['total_profit'])
axes[0, 1].set_title('Total Profit')
axes[0, 1].tick_params(axis='x', rotation=45)

# =========================
# 3. Load Factor
# =========================
axes[0, 2].bar(aircraft, aircraft_performance['avg_load_factor'])
axes[0, 2].set_title('Load Factor (%)')
axes[0, 2].tick_params(axis='x', rotation=45)

# =========================
# 4. Fuel Cost
# =========================
axes[1, 0].bar(aircraft, aircraft_performance['avg_fuel_cost'])
axes[1, 0].set_title('Fuel Cost')
axes[1, 0].tick_params(axis='x', rotation=45)

# =========================
# 5. Loss Flights
# =========================

total_flights = df.groupby('Aircraft_Type').size()

aircraft_performance['total_flights'] = aircraft_performance['Aircraft_Type'].map(total_flights)

aircraft_performance['loss_percentage'] = (
    aircraft_performance['loss_flights'] /
    aircraft_performance['total_flights']
) * 100

axes[1, 1].bar(aircraft, aircraft_performance['loss_percentage'])
axes[1, 1].set_title('Loss Flights (%)')
axes[1, 1].set_ylabel('Percentage (%)')
axes[1, 1].tick_params(axis='x', rotation=45)


# axes[1, 1].bar(aircraft, aircraft_performance['loss_flights'])
# axes[1, 1].set_title('Loss Flights')
# axes[1, 1].tick_params(axis='x', rotation=45)

# =========================
# Remove empty subplot
# =========================
axes[1, 2].axis('off')

# =========================
# Layout fix
# =========================
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(7,7))

plt.pie(
    cost_structure['avg_cost'],
    labels=cost_structure['cost_type'],
    autopct='%1.1f%%',
    startangle=90
)

plt.title('Cost Structure')

plt.tight_layout()
plt.show()

# PART 8: STATISTICAL ANALYSIS 1 - Z-SCORE OUTLIER DETECTION

df['Profit_Margin_Zscore'] = stats.zscore(df['Profit_Margin'])
df['Is_Outlier_Zscore'] = df['Profit_Margin_Zscore'].abs() > 3

outliers = df[df['Is_Outlier_Zscore']].copy()
print(f"Total outlier flights (|Z| > 3): {len(outliers)} ({len(outliers)/len(df)*100:.2f}% of all flights)")
print()

if len(outliers) > 0:
    outlier_summary = (
        outliers.groupby('Destination')
        .agg(
            outlier_flights=('Profit_Margin', 'count'),
            avg_zscore=('Profit_Margin_Zscore', 'mean'),
            avg_profit_margin=('Profit_Margin', 'mean'),
        )
        .round(2)
        .sort_values('outlier_flights', ascending=False)
        .reset_index()
    )
    print("Outliers by destination:")
    print(outlier_summary.to_string(index=False))
    print()

    print("Top 10 most extreme outlier flights:")
    top_outliers = outliers.reindex(
        outliers['Profit_Margin_Zscore'].abs().sort_values(ascending=False).index
    )[['ID', 'Destination', 'Season', 'Profit_Margin', 'Profit_Margin_Zscore']].head(10)
    print(top_outliers.round(2).to_string(index=False))
print()

zscore_summary = {
    'total_outliers': int(len(outliers)),
    'outlier_pct': round(len(outliers) / len(df) * 100, 2),
    'mean_profit_margin': round(df['Profit_Margin'].mean(), 4),
    'std_profit_margin': round(df['Profit_Margin'].std(), 4),
}

# PART 9: STATISTICAL ANALYSIS 2 - ONE-WAY ANOVA

anova_results = {}

# ANOVA 1: Profit Margin across Seasons
groups_season = [g['Profit_Margin'].values for _, g in df.groupby('Season')]
f_stat, p_val = stats.f_oneway(*groups_season)
anova_results['season'] = {'f_statistic': round(f_stat, 4), 'p_value': p_val, 'significant': bool(p_val < 0.05)}
print(f"1) Profit_Margin ~ Season:")
print(f"   F-statistic = {f_stat:.4f}, p-value = {p_val:.2e}")
print(f"   {'SIGNIFICANT' if p_val < 0.05 else 'NOT significant'} (alpha=0.05): season has a {'real' if p_val<0.05 else 'no real'} effect on profit margin")
print()

# ANOVA 2: Profit Margin across Route Categories
groups_route = [g['Profit_Margin'].values for _, g in df.groupby('Route_Category')]
f_stat2, p_val2 = stats.f_oneway(*groups_route)
anova_results['route_category'] = {'f_statistic': round(f_stat2, 4), 'p_value': p_val2, 'significant': bool(p_val2 < 0.05)}
print(f"2) Profit_Margin ~ Route_Category:")
print(f"   F-statistic = {f_stat2:.4f}, p-value = {p_val2:.2e}")
print(f"   {'SIGNIFICANT' if p_val2 < 0.05 else 'NOT significant'} (alpha=0.05): route category has a {'real' if p_val2<0.05 else 'no real'} effect on profit margin")
print()

# ANOVA 3: Profit Margin across Aircraft Types
groups_aircraft = [g['Profit_Margin'].values for _, g in df.groupby('Aircraft_Type')]
f_stat3, p_val3 = stats.f_oneway(*groups_aircraft)
anova_results['aircraft_type'] = {'f_statistic': round(f_stat3, 4), 'p_value': p_val3, 'significant': bool(p_val3 < 0.05)}
print(f"3) Profit_Margin ~ Aircraft_Type:")
print(f"   F-statistic = {f_stat3:.4f}, p-value = {p_val3:.2e}")
print(f"   {'SIGNIFICANT' if p_val3 < 0.05 else 'NOT significant'} (alpha=0.05): aircraft type has a {'real' if p_val3<0.05 else 'no real'} effect on profit margin")
print()

# PART 10: STATISTICAL ANALYSIS 3 - PEARSON CORRELATION

pearson_results = {}

pairs = [
    ('Load_Factor', 'Profit_Margin', 'Load Factor vs Profit Margin'),
    ('Flight_Hours', 'Profit_Margin', 'Flight Hours vs Profit Margin'),
    ('Total_Revenue', 'Total_Cost', 'Total Revenue vs Total Cost'),
    ('Passengers', 'Profit', 'Passengers vs Profit'),
    ('Fuel_Cost', 'Profit_Margin', 'Fuel Cost vs Profit Margin'),
]

for col_x, col_y, label in pairs:
    r, p = stats.pearsonr(df[col_x], df[col_y])
    pearson_results[label] = {'r': round(r, 4), 'p_value': p}
    strength = (
        'very strong' if abs(r) >= 0.8 else
        'strong' if abs(r) >= 0.6 else
        'moderate' if abs(r) >= 0.4 else
        'weak' if abs(r) >= 0.2 else
        'very weak / none'
    )
    direction = 'positive' if r > 0 else 'negative'
    print(f"{label}: r = {r:.4f}  (p = {p:.2e})  -> {strength} {direction} correlation")

print()

# Full correlation matrix for key numeric variables
print("Correlation matrix (key variables):")
corr_cols = ['Load_Factor', 'Flight_Hours', 'Passengers', 'Total_Revenue',
             'Total_Cost', 'Fuel_Cost', 'Profit', 'Profit_Margin']
corr_matrix = df[corr_cols].corr(method='pearson').round(3)
print(corr_matrix.to_string())
print()

# PART 6: ANALYSIS 5 - LOAD FACTOR vs PROFIT  (علاقة نسبة الامتلاء بالربح)

def load_factor_bucket(lf):
    if lf < 0.60:
        return 'Below 60%'
    elif lf < 0.70:
        return '60% - 70%'
    elif lf < 0.80:
        return '70% - 80%'
    elif lf < 0.90:
        return '80% - 90%'
    else:
        return 'Above 90%'

df['Load_Factor_Bucket'] = df['Load_Factor'].apply(load_factor_bucket)
_bucket_order = ['Below 60%', '60% - 70%', '70% - 80%', '80% - 90%', 'Above 90%']

load_factor_analysis = (
    df.groupby('Load_Factor_Bucket')
    .agg(
        total_flights=('Profit', 'count'),
        avg_profit_margin=('Profit_Margin', 'mean'),
        avg_revenue=('Total_Revenue', 'mean'),
        avg_cost=('Total_Cost', 'mean'),
        loss_flights=('Profit', lambda x: (x < 0).sum()),
    )
    .round(2)
    .reindex(_bucket_order)
    .sort_values('avg_profit_margin', ascending=False)
    .reset_index()
)
print(load_factor_analysis.to_string(index=False))
print()

# PART 11: EXPORT ALL RESULTS TO JSON (for dashboard - real numbers, not mockup)

def df_to_records(d):
    return json.loads(d.to_json(orient='records'))

dashboard_data = {
    'meta': {
        'title': 'Airline Route Profitability Analysis',
        'airline': 'Emirates Airlines (EK)',
        'hub': 'Dubai (DXB)',
        'year': 2024,
        'total_flights': overall['total_flights'],
        'destinations': int(df['Destination'].nunique()),
    },
    'overall': overall,
    'route_profitability': df_to_records(route_profitability),
    'season_profitability': df_to_records(season_profitability),
    'aircraft_performance': df_to_records(aircraft_performance),
    'load_factor_analysis': df_to_records(load_factor_analysis),
    'cost_structure': df_to_records(cost_structure),
    'statistics': {
        'zscore': {
            **zscore_summary,
            'outliers_by_destination': df_to_records(outlier_summary) if len(outliers) > 0 else [],
            'top_outlier_flights': df_to_records(
                outliers.reindex(outliers['Profit_Margin_Zscore'].abs().sort_values(ascending=False).index)
                [['ID', 'Destination', 'Season', 'Route_Category', 'Profit_Margin', 'Profit_Margin_Zscore']]
                .head(15).round(2)
            ) if len(outliers) > 0 else [],
        },
        'anova': anova_results,
        'pearson': {
            'pairs': pearson_results,
            'correlation_matrix': json.loads(corr_matrix.to_json()),
        },
    },
}

with open('dashboard_data.json', 'w', encoding='utf-8') as f:
    json.dump(dashboard_data, f, indent=2, ensure_ascii=False, default=str)

print("Saved: dashboard_data.json")

# Also export key tables to CSV for reference / Excel re-import if needed
route_profitability.to_csv('output_route_profitability.csv', index=False)
season_profitability.to_csv('output_season_profitability.csv', index=False)
aircraft_performance.to_csv('output_aircraft_performance.csv', index=False)
load_factor_analysis.to_csv('output_load_factor_analysis.csv', index=False)
cost_structure.to_csv('output_cost_structure.csv', index=False)
outliers[['ID', 'Destination', 'Season', 'Route_Category', 'Profit_Margin', 'Profit_Margin_Zscore']].to_csv('output_zscore_outliers.csv', index=False)

print("Saved: output_*.csv (5 summary tables + outliers list)")
print()
print("=" * 80)
print("ANALYSIS COMPLETE")
print("=" * 80)